/** Export only the auditable arena harness, never the private website or env. */
import { cp, mkdir, writeFile, access } from 'node:fs/promises';
import path from 'node:path';

const destination = process.argv[2];
if (!destination) throw new Error('Usage: node scripts/tetris-bench/export-public.mjs <new-directory>');
const root = path.resolve(destination);
try { await access(root); throw new Error('Destination must not exist'); }
catch (error) { if (error.code !== 'ENOENT') throw error; }
await mkdir(root, { recursive: true });
for (const entry of ['lib/tetris-bench', 'scripts/tetris-bench', 'docs/tetris-bench-rules.md']) {
  await mkdir(path.dirname(path.join(root, entry)), { recursive: true });
  await cp(entry, path.join(root, entry), { recursive: true, filter: (source) => !source.endsWith('/data.ts') });
}
await writeFile(path.join(root, 'package.json'), JSON.stringify({
  name: 'tetris-bench', version: '1.0.0', private: true, type: 'module', engines: { node: '>=24' },
  scripts: { test: 'node --test scripts/tetris-bench/*.test.ts', 'bench:run': 'node scripts/tetris-bench/run.ts' },
}, null, 2) + '\n');
await writeFile(path.join(root, '.gitignore'), 'node_modules/\n.env*\npublic/tetris-bench/\n');
await mkdir(path.join(root, '.github/workflows'), { recursive: true });
await writeFile(path.join(root, '.github/workflows/check.yml'), `name: Harness checks
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm test
`);
await writeFile(path.join(root, 'README.md'), `# Tetris Bench

Decision models play Tetris through one typed contract. IQ pauses gravity while a brain answers. Blitz gives it at most 100 ms. Both modes count equally towards CR.

The website lives at [lowndes.dev/tetris-bench](https://www.lowndes.dev/tetris-bench). This repository contains the auditable engine, adapters, harness, rating code, runner and tests.

## Run

Node.js 24 or newer is required. The harness has no package dependencies.

\`\`\`sh
npm test
npm run bench:run -- --help
\`\`\`

Read [the frozen rules and adapter contract](docs/tetris-bench-rules.md) before running a tournament or submitting an adapter. Run the full five-seed suite for official CR. Quick and custom-limit runs are separate from official results.

Provider credentials belong in environment variables. Never commit keys or raw provider error bodies. Local brains need no credentials. Jev uses OpenRouter's System One endpoint; the LLM classifier uses structured JSON output.

## Enter

Open a pull request adding an adapter and its tests. It must implement the same typed contract as every other brain. Include model identity, timeout and cancellation behaviour, and cost reporting. Ratings are generated by server or CLI jobs, never trusted from a browser.

The behavioural ruleset is \`tetris-bench@1\`. Behavioural changes require a new ruleset version and a fresh rating field.
`);
console.log(root);
